# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Extractor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  
  # Pods for Extractor
  pod 'Firebase/Core' => '5.5.0'
  pod 'Firebase/MLVision' => '5.5.0'
  pod 'Firebase/MLVisionTextModel' => '5.5.0'

end
